openapi: 3.0.0
info:
  title: Booking API Dcos
  version: 1.0.0
servers:
  - url: http://localhost:3000
components:
  schemas:
    Booking:
      type: object
      properties:
        title:
          type: string
          description: "Booking Title"
        desc:
          type: string
          description: "Booking Description"
        amount:
          type: number
          description: "Booking amount"
paths:
  /bookings/create:
    post:
      tags:
        - bookings
      summary: Create new booking
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#components/schemas/Booking"
      responses:
        "200":
          description: booking created successfully
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Booking"
        "400":
          description: "Bad request invalid booking details"
